version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-gpt-3.5-turbo}
      - TEMPERATURE=${TEMPERATURE:-0.1}
      - MAX_TOKENS=${MAX_TOKENS:-1024}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME:-keepitreal/vietnamese-sbert}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "8501:8000"
    environment:
      - API_URL=http://api:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    depends_on:
      - api